apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems
  labels:
    app: ems-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-app
  template:
    metadata:
      labels:
        app: ems-app
    spec:
      containers:
      - name: ems-app-cont
        image: skzakeer27/ems:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: ems-app
spec:
  selector:
    app: ems-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
